name: Java CI with Maven

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'
      - name: Build with Maven (verify + coverage)
        run: mvn -B verify
      - name: Upload reports
        uses: actions/upload-artifact@v4
        with:
          name: reports
          path: |
            target/surefire-reports/*.xml
            target/site/jacoco/index.html
